### ISSUE TITLE
Segmentation fault when accessing :contains selector with modest engine

### ISSUE THREAD

**Issue by lorien** [rushter/selectolax#145]
```
from selectolax.parser import HTMLParser

dom = HTMLParser("<div><ul><li>foo</li></ul></div>")
print(dom.css('li:contains("foo")'))
```
I do not expect `:contains()` selector work, it is not in CSS selectors standard.
But at least the program should not end with segfault.

**Comment by rushter** [comment]
`HTMLParser` has a fragile parsing logic in the upstream library. The only way to avoid this is to use newer backed:

```
>>> from selectolax.lexbor import LexborHTMLParser
>>> dom = LexborHTMLParser("<div><ul><li>foo</li></ul></div>")
>>> print(dom.css('li:contains("foo")'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "selectolax/lexbor.pyx", line 177, in selectolax.lexbor.LexborHTMLParser.css
    return self.root.css(query)
  File "selectolax/lexbor/node.pxi", line 193, in selectolax.lexbor.LexborNode.css
    return self.parser.selector.find(query, self)
  File "selectolax/lexbor/selection.pxi", line 36, in selectolax.lexbor.LexborCSSSelector.find
    cpdef find(self, str query, LexborNode node):
  File "selectolax/lexbor/selection.pxi", line 48, in selectolax.lexbor.LexborCSSSelector.find
    raise SelectolaxError("Can't parse CSS selector.")
selectolax.lexbor.SelectolaxError: Can't parse CSS selector.
```
